apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-29T19:15:58Z"
  labels:
    run: vault
  name: vault
  namespace: default
  resourceVersion: "1330"
  uid: d103163e-16b8-41a2-8ed4-ed789c4f6c94
spec:
  clusterIP: 10.110.6.32
  clusterIPs:
  - 10.110.6.32
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31248
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    run: vault
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
