apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: anis
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "anis"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: reg
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "reg"