apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:        
        - name: lab2
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
          - name: REACT_APP_USERNAME
            value: anis
          - name: REACT_APP_COMPANY_NAME
            value: reg
          ports:
            - containerPort: 3000