apiVersion: v1
kind: Service
metadata:
  name: lab2
  labels:
    name: lab2
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: lab2
  type: NodePort